// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOwr9pofiHjGe1o46zH0RgKScX2e93HbE',
    appId: '1:41737672431:web:b8668582a4a9b7f63c6d1a',
    messagingSenderId: '41737672431',
    projectId: 'hackit-4bit',
    authDomain: 'hackit-4bit.firebaseapp.com',
    storageBucket: 'hackit-4bit.firebasestorage.app',
    measurementId: 'G-VGW261Q6SY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSeD0VEIwjxZ9vlbceQ7UGk22t93rUBig',
    appId: '1:41737672431:android:60f67d57f54598833c6d1a',
    messagingSenderId: '41737672431',
    projectId: 'hackit-4bit',
    storageBucket: 'hackit-4bit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBAr54woUMJfI2K8y_6x7exI6Io4-_mb0',
    appId: '1:41737672431:ios:ad2dae827c73ce073c6d1a',
    messagingSenderId: '41737672431',
    projectId: 'hackit-4bit',
    storageBucket: 'hackit-4bit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4bit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBAr54woUMJfI2K8y_6x7exI6Io4-_mb0',
    appId: '1:41737672431:ios:ad2dae827c73ce073c6d1a',
    messagingSenderId: '41737672431',
    projectId: 'hackit-4bit',
    storageBucket: 'hackit-4bit.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication4bit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOwr9pofiHjGe1o46zH0RgKScX2e93HbE',
    appId: '1:41737672431:web:47fbb3b30da20ab83c6d1a',
    messagingSenderId: '41737672431',
    projectId: 'hackit-4bit',
    authDomain: 'hackit-4bit.firebaseapp.com',
    storageBucket: 'hackit-4bit.firebasestorage.app',
    measurementId: 'G-G3KFBBHPXS',
  );
}